dist: trusty
sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r test_requirements.txt
before_script:
  - psql -c 'create role handy login createdb;' -U postgres
script:
  - py.test
